### ISSUE TITLE
HubInterface::_parse_msg message:: ERROR - received non-success reply token: 4

### ISSUE THREAD

**Issue by maqadri** [CleverPet/hackerpet#24]
I pushed the sample "101_TestingSequence.cpp" without any changes. After it flashed, it quickly showed a "hard fault" error signal (SOS blink - 1 red blink - SOS blink and restarted). I received (in the Particle Workbench console):
```
0000001117 [app] INFO: setting all lights off
0000002117 [app] INFO: setting cue light on
0000003100 [app.hackerpet] ERROR: HubInterface::_parse_msg message:: ERROR - received non-success reply token: 4
```

Not sure if this is an issue with a mis-matched library version somewhere or indicative of hardware failure.

Some context:
The device had not been used for about three months. Tonight, I opened the case and set the photon into setup mode to setup a new WiFi. The previous program at that time (not a standard program) was active and functioning, and my animal was interacting with it successfully (selecting pads, getting food; Cleverpet was showing lights, reacting appropriately, updating Google sheets reports, etc.). I pushed the stock 007_LearningBrightness.cpp and it hard faulted. I re-flashed my custom game and it hard faulted. I commented out everything within of 007_LearningBrightness.cpp's `void loop` except `hub.Run(20);` and it did not hard fault; I uncommented just the `hub.Run(20);` and it hard faulted. It provided the same app.hackerpet error line in the console.

**Comment by JelmerT** [comment]
Thanks for submitting this issue @maqadri !

We are aware of an issue with the library not working as it should with the latest version of Particle device OS. Could you try compiling and flashing against Device Target OS 1.5.1? 
That might be an intermediate solution until we update the library.

**Comment by maqadri** [comment]
That fixes the issue. Thanks.
